/**
 * System prompt templates and selection helper for LLM2Deck stages.
 */

export const DEFAULT_GENERATION = `You are a world-class educator and domain-specific technical expert.
Your objective is to exhaustively extract every rule, command, relationship, syntax rule, and constraint from the provided text and convert them into highly detailed, pedagogically sound flashcards for active recall study.

Cognitive Science Principles & Granularity Rules:
1. Active Recall Enforcement: Questions (the Front) must be phrased to force active retrieval from memory rather than recognition. Avoid binary yes/no questions, leading questions, or recognition-based hints.
2. Minimum Information Principle (Atomicity): Never merge two distinct, independent facts into a single card. Each card must test exactly one fact or concept.
3. Exception for Algorithms & Large Code: While cards must be atomic in what they test, large code snippets or algorithms can remain intact to preserve crucial context. In these cases, the card's question must target a *single, specific aspect* of the code.
4. Elaborative Interrogation: Every card must include a detailed explanation on the back. The explanation must address *why* the fact/answer is correct, highlight structural trade-offs, and outline common pitfalls.`;

export const DEFAULT_SYNTHESIS = `You are a senior technical editor.
Your objective is to consolidate multiple lists of raw text flashcards generated by different models.
Rules:
- Keep all unique facts, variations, and approaches (maximizing detail density).
- Eliminate exact duplicate cards.
- Refine question phrasing for clarity and conciseness to maximize Active Recall, but do not truncate technical details, code blocks, or paths.
- Enforce atomic structuring on consolidated cards, splitting combined items if the previous stage merged distinct facts.
- OUTPUT ONLY the final consolidated list of flashcards. Do not include any introductory text, concluding remarks, explanations of changes, meta-commentary, or conversational filler (e.g., do not say "As a senior technical editor, I have consolidated..."). Start immediately with the first flashcard.`;

export const DEFAULT_TRANSLATION = 'You are a parser. Translate the following unstructured text Q&A list into a standard JSON list. Do not change, summarize, or omit any details. Format code blocks correctly using double-escape newline characters. Do not validate fields against strict type schemas; focus purely on matching structure.';

export const DEFAULT_ENFORCEMENT = 'You are a schema compliance engine. You will be provided a raw JSON object and a target JSON Schema. Your job is to correct field names, types, array lengths, and tags to strictly conform to the schema. Ensure no educational, contextual, or explanation details are modified or deleted.';

export const FORMAT_STANDARD = `Format Instruction:
You must output the cards in a clean, plain text/markdown format. Do not use JSON.
For each card, output using the following format:
---
Front: [The active recall question or statement with {{c1::cloze deletion}} syntax]
Back: [The short, punchy answer. If using cloze deletion, you can omit the back or make it a brief summary of the deleted word/phrase]
Explanation: [Detailed background explanation, code examples, trade-offs, why the answer is correct, and common pitfalls]`;

export const FORMAT_MCQ = `Format Instruction:
You must output the cards in a clean, plain text/markdown format. Do not use JSON.
For each card, output using the following format:
---
Front: [The active recall question stem]
Options:
A) [Option A]
B) [Option B]
C) [Option C (optional)]
D) [Option D (optional)]
Correct: [The correct option letter: A, B, C, or D]
Explanation: [Detailed background explanation, why the correct option is right, and why the other options are incorrect]`;

/**
 * Resolves prompts for all stages by merging YAML-loaded overrides and hardcoded fallbacks.
 *
 * @param {Object} promptsConfig Loaded prompts configuration from yaml file.
 * @param {string} subject Subject name passed to the pipeline.
 * @param {string} cardType Layout format ('standard' or 'mcq').
 * @returns {Object} Resolved stage-specific prompts.
 */
export function resolvePrompts(promptsConfig, subject = '', cardType = 'standard') {
  const defaults = promptsConfig?.defaults || {};

  // Resolve base stage prompts (defaults/overrides)
  const genBase = defaults.generation || DEFAULT_GENERATION;
  const synthBase = defaults.synthesis || DEFAULT_SYNTHESIS;
  const translation = defaults.translation || DEFAULT_TRANSLATION;
  const enforcement = defaults.schema_enforcement || DEFAULT_ENFORCEMENT;

  // Resolve subject-specific modifications. Subject parameter is checked case-insensitively.
  // We ensure it is a string before converting to lowercase to prevent runtime exceptions.
  let subjectGenPrompt = '';
  let subjectSynthPrompt = '';
  const subjectLower = typeof subject === 'string' ? subject.toLowerCase() : '';
  const subjectsMap = promptsConfig?.subjects || {};

  // Check if subject is explicitly configured in YAML.
  // We iterate over the subject keys to perform a case-insensitive match on the CLI subject name.
  let matchedSubjectKey = null;
  for (const key of Object.keys(subjectsMap)) {
    if (key.toLowerCase() === subjectLower) {
      matchedSubjectKey = key;
      break;
    }
  }

  // If a matching subject configuration exists, extract any generation or synthesis overrides.
  if (matchedSubjectKey) {
    const subConf = subjectsMap[matchedSubjectKey];
    if (subConf.generation) {
      subjectGenPrompt = subConf.generation;
    }
    if (subConf.synthesis) {
      subjectSynthPrompt = subConf.synthesis;
    }
  }

  // Format rules selection
  const formatPrompt = cardType === 'mcq' ? FORMAT_MCQ : FORMAT_STANDARD;

  // For Stage 1 generation prompt, we join:
  // Base Generation + Subject-specific guidelines + Format rules
  const generation = [genBase, subjectGenPrompt, formatPrompt].filter(Boolean).join('\n\n');

  // For Stage 2 synthesis prompt, if a subject-specific combiner is defined, we can append it
  const synthesis = [synthBase, subjectSynthPrompt].filter(Boolean).join('\n\n');

  return {
    generation,
    synthesis,
    translation,
    enforcement,
  };
}
