/**
 * System prompt templates and selection helper for LLM2Deck stages.
 */

export const DEFAULT_GENERATION = `You are a world-class educator and domain-specific technical expert.
Your objective is to generate comprehensive, highly detailed flashcards to exhaustively cover the given topic, explaining the core concepts, syntax, rules, and best practices. Your goal is to systematically build, expand, and solidify the user's knowledge on this subject using active recall.

Cognitive Science Principles & Granularity Rules:
1. Active Recall Enforcement: Questions (the Front) must be phrased to force active retrieval from memory rather than recognition. Avoid binary yes/no questions, leading questions, or recognition-based hints.
2. Minimum Information Principle (Atomicity): Never merge two distinct, independent facts into a single card. Each card must test exactly one fact or concept.
3. Exception for Algorithms & Large Code: While cards must be atomic in what they test, large code snippets or algorithms can remain intact to preserve crucial context. In these cases, the card's question must target a *single, specific aspect* of the code.
4. Elaborative Interrogation: Every card must include a detailed explanation on the back. The explanation must address *why* the fact/answer is correct, highlight structural trade-offs, and outline common pitfalls.`;

export const DEFAULT_GENERATION_DOCUMENT = `You are a world-class document analysis and digestion engine.
Your objective is to exhaustively extract every single rule, command, configuration setting, relationship, syntax rule, code example, trade-off, and constraint directly from the provided document content. You must convert all extracted information into highly detailed, pedagogically sound flashcards for active recall study. Do not summarize, generalize, or skip any technical details; ensure absolute and complete coverage of the text, leaving no key details or facts behind.

Cognitive Science Principles & Granularity Rules:
1. Active Recall Enforcement: Questions (the Front) must be phrased to force active retrieval from memory rather than recognition. Avoid binary yes/no questions, leading questions, or recognition-based hints.
2. Minimum Information Principle (Atomicity): Never merge two distinct, independent facts into a single card. Each card must test exactly one fact or concept.
3. Exception for Algorithms & Large Code: While cards must be atomic in what they test, large code snippets or algorithms can remain intact to preserve crucial context. In these cases, the card's question must target a *single, specific aspect* of the code.
4. Elaborative Interrogation: Every card must include a detailed explanation on the back. The explanation must address *why* the fact/answer is correct, highlight structural trade-offs, and outline common pitfalls.`;

export const DEFAULT_SYNTHESIS = `You are a senior technical editor.
Your objective is to consolidate multiple lists of raw text flashcards generated by different models.
Rules:
- Keep all unique facts, variations, and approaches (maximizing detail density).
- Eliminate exact duplicate cards.
- Refine question phrasing for clarity and conciseness to maximize Active Recall, but do not truncate technical details, code blocks, or paths.
- Enforce atomic structuring on consolidated cards, splitting combined items if the previous stage merged distinct facts.
- OUTPUT ONLY the final consolidated list of flashcards. Do not include any introductory text, concluding remarks, explanations of changes, meta-commentary, or conversational filler (e.g., do not say "As a senior technical editor, I have consolidated..."). Start immediately with the first flashcard.`;

// The enforcement engine is provided a plain text/markdown list from the synthesis stage (Stage 2)
// and converts it into a compliant JSON structure matching CARD_JSON_SCHEMA.
export const DEFAULT_ENFORCEMENT = 'You are a schema compliance engine. You will be provided a plain text/markdown list of consolidated flashcards and a target JSON Schema. Your job is to parse and convert this list into a JSON object that strictly conforms to the schema, correcting any field names, types, array lengths, or formats to meet the schema requirements. Ensure no educational, contextual, or explanation details are modified or deleted.';

export const FORMAT_STANDARD = `Format Instruction:
You must output the cards in a clean, plain text/markdown format. Do not use JSON.
For each card, choose the most appropriate layout: either a Basic Q&A card or a Cloze deletion card.

For each card, output using one of the following formats:

Format 1: Basic Q&A Card
---
Front: [A clear, active recall question that does not use cloze deletion syntax]
Back: [The short, punchy answer to the question]
Explanation: [Detailed background explanation, code examples, trade-offs, why the answer is correct, and common pitfalls]

Format 2: Cloze Deletion Card
---
Front: [An active recall statement containing one or more cloze deletions using {{c1::cloze deletion}} syntax]
Back: [The short, punchy answer. If using cloze deletion, you can omit the back or make it a brief summary of the deleted word/phrase]
Explanation: [Detailed background explanation, code examples, trade-offs, why the answer is correct, and common pitfalls]`;

export const FORMAT_MCQ = `Format Instruction:
You must output the cards in a clean, plain text/markdown format. Do not use JSON.
For each card, output using the following format:
---
Front: [The active recall question stem]
Options:
A) [Option A]
B) [Option B]
C) [Option C (optional)]
D) [Option D (optional)]
Correct: [The correct option letter: A, B, C, or D]
Explanation: [Detailed background explanation, why the correct option is right, and why the other options are incorrect]`;

/**
 * Resolves prompts for all stages by merging YAML-loaded overrides and hardcoded fallbacks.
 *
 * @param {Object} promptsConfig Loaded prompts configuration from yaml file.
 * @param {string} subject Subject name passed to the pipeline.
 * @param {string} cardType Layout format ('standard' or 'mcq').
 * @returns {Object} Resolved stage-specific prompts.
 */
export function resolvePrompts(promptsConfig, subject = '', cardType = 'standard', mode = null) {
  const defaults = promptsConfig?.defaults || {};

  // Resolve subject-specific modifications. Subject parameter is checked case-insensitively.
  // We ensure it is a string before converting to lowercase to prevent runtime exceptions.
  const subjectLower = typeof subject === 'string' ? subject.toLowerCase() : '';
  const subjectsMap = promptsConfig?.subjects || {};

  // Check if subject is explicitly configured in YAML.
  // We iterate over the subject keys to perform a case-insensitive match on the CLI subject name.
  let matchedSubjectKey = null;
  for (const key of Object.keys(subjectsMap)) {
    if (key.toLowerCase() === subjectLower) {
      matchedSubjectKey = key;
      break;
    }
  }

  // Determine active generation mode ('topic' or 'document') to select the appropriate
  // default system prompt.
  // 1. Prioritize explicit option passed to the function parameter
  // 2. Query subject configuration in YAML prompts config
  // 3. Fallback to 'topic' as the default mode
  let resolvedMode = mode;
  if (!resolvedMode && matchedSubjectKey) {
    const subConf = subjectsMap[matchedSubjectKey];
    if (subConf && subConf.mode === 'document') {
      resolvedMode = 'document';
    }
  }
  if (!resolvedMode) {
    resolvedMode = 'topic';
  }

  // Resolve base stage prompts (defaults/overrides)
  // For document mode, we look for generation_document override first, then standard
  // generation override, then fallback to DEFAULT_GENERATION_DOCUMENT.
  // For other modes, we look for standard generation override, then fallback to DEFAULT_GENERATION.
  let genBase;
  if (resolvedMode === 'document') {
    genBase = defaults.generation_document || defaults.generation || DEFAULT_GENERATION_DOCUMENT;
  } else {
    genBase = defaults.generation || DEFAULT_GENERATION;
  }
  const synthBase = defaults.synthesis || DEFAULT_SYNTHESIS;

  const enforcement = defaults.schema_enforcement || DEFAULT_ENFORCEMENT;

  let subjectGenPrompt = '';
  let subjectSynthPrompt = '';

  // If a matching subject configuration exists, extract any generation or synthesis overrides.
  if (matchedSubjectKey) {
    const subConf = subjectsMap[matchedSubjectKey];
    if (subConf.generation) {
      subjectGenPrompt = subConf.generation;
    }
    if (subConf.synthesis) {
      subjectSynthPrompt = subConf.synthesis;
    }
  }

  // Format rules selection
  const formatPrompt = cardType === 'mcq' ? FORMAT_MCQ : FORMAT_STANDARD;

  // For Stage 1 generation prompt, we join:
  // Base Generation + Subject-specific guidelines + Format rules
  const generation = [genBase, subjectGenPrompt, formatPrompt].filter(Boolean).join('\n\n');

  // For Stage 2 synthesis prompt, we join the base synthesis prompt, subject-specific combiner,
  // and the target formatting rules (Basic/Cloze or MCQ) to ensure output format is preserved.
  const synthesis = [synthBase, subjectSynthPrompt, formatPrompt].filter(Boolean).join('\n\n');

  return {
    generation,
    synthesis,
    enforcement,
  };
}

export const CARD_JSON_SCHEMA = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    title: { type: 'string', description: 'Title of the concept, problem, or document section.' },
    topic: { type: 'string', description: 'Main category hierarchy or path.' },
    difficulty: {
      type: 'string',
      enum: ['Basic', 'Intermediate', 'Advanced'],
      description: 'Standardized difficulty level for database sorting.',
    },
    cards: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          card_format: {
            type: 'string',
            enum: ['Basic', 'Cloze', 'MCQ'],
            description: 'The structural layout of the card in Anki.',
          },
          card_type: {
            type: 'string',
            enum: ['Concept', 'Code', 'Procedure', 'Syntax', 'Behavior', 'Constraint', 'ErrorHandling', 'TradeOff'],
            description: 'Pedagogical tag for sorting and styled headers.',
          },
          tags: {
            type: 'array',
            items: { type: 'string', pattern: '^[A-Za-z0-9-_/]+$' },
            description: 'Alphanumeric, hyphen, underscore, and slash tags (no spaces allowed).',
          },
          front: { type: 'string', description: 'Front/question side of the card, or statement with {{c1::hidden text}} syntax for Cloze.' },
          back: { type: 'string', description: 'Short, punchy answer. Required for Basic card format; prohibited in MCQ or Cloze.' },
          options: {
            type: 'array',
            items: { type: 'string' },
            minItems: 2,
            maxItems: 4,
            description: '2 to 4 choices. Required only for MCQ.',
          },
          correct_answer: {
            type: 'string',
            enum: ['A', 'B', 'C', 'D'],
            description: 'Correct choice letter index. Required only for MCQ.',
          },
          explanation: {
            type: 'string',
            description: 'Detailed background explanation, code examples, or trade-offs shown on the back side of all card formats.',
          },
        },
        required: ['card_format', 'card_type', 'tags', 'explanation'],
        additionalProperties: false,
        oneOf: [
          {
            properties: {
              card_format: { const: 'Basic' },
              options: { not: {} },
              correct_answer: { not: {} },
            },
            required: ['front', 'back'],
          },
          {
            properties: {
              card_format: { const: 'Cloze' },
              front: { pattern: '\\{\\{c[0-9]+::' },
              back: { not: {} },
              options: { not: {} },
              correct_answer: { not: {} },
            },
            required: ['front'],
            description: 'front must contain at least one cloze deletion using {{c1::word}} syntax.',
          },
          {
            properties: {
              card_format: { const: 'MCQ' },
              back: { not: {} },
            },
            required: ['front', 'options', 'correct_answer'],
          },
        ],
        allOf: [
          {
            if: {
              properties: {
                card_format: { const: 'MCQ' },
                correct_answer: { const: 'C' },
              },
              required: ['card_format', 'correct_answer'],
            },
            then: {
              properties: {
                options: { minItems: 3 },
              },
            },
          },
          {
            if: {
              properties: {
                card_format: { const: 'MCQ' },
                correct_answer: { const: 'D' },
              },
              required: ['card_format', 'correct_answer'],
            },
            then: {
              properties: {
                options: { minItems: 4 },
              },
            },
          },
        ],
      },
    },
  },
  required: ['title', 'topic', 'difficulty', 'cards'],
  additionalProperties: false,
};
