# Questions

QUESTIONS = [
    "Contains Duplicate",
    "Valid Anagram",
    "Two Sum",
    "Group Anagrams",
    "Top K Frequent Elements",
    "Encode and Decode Strings",
    "Product of Array Except Self",
    "Valid Sudoku",
    "Longest Consecutive Sequence",
    "Valid Palindrome",
    "Two Sum II Input Array Is Sorted",
    "3Sum",
    "Container With Most Water",
    "Trapping Rain Water",
    "Best Time to Buy And Sell Stock",
    "Longest Substring Without Repeating Characters",
    "Longest Repeating Character Replacement",
    "Permutation In String",
    "Minimum Window Substring",
    "Sliding Window Maximum",
    "Valid Parentheses",
    "Min Stack",
    "Evaluate Reverse Polish Notation",
    "Daily Temperatures",
    "Car Fleet",
    "Largest Rectangle In Histogram",
]

CS_QUESTIONS = [
    "How does a Hash Map work internally?",
    # "The difference between Process and Thread",
    # "How does Garbage Collection work?",
    # "TCP vs UDP",
    # "What happens when you type a URL into a browser?",
    # "Big O Notation and Time Complexity",
    # "Virtual Memory and Paging",
    # "CAP Theorem",
    # "ACID properties in Databases",
    # "Public Key Cryptography (RSA)",
]
