# Questions

QUESTIONS = [
    "Contains Duplicate",
    "Valid Anagram",
    "Two Sum",
    "Group Anagrams",
    "Top K Frequent Elements",
    "Encode and Decode Strings",
    "Product of Array Except Self",
    "Valid Sudoku",
    "Longest Consecutive Sequence",
    "Valid Palindrome",
    "Two Sum II Input Array Is Sorted",
    "3Sum",
    "Container With Most Water",
    "Trapping Rain Water",
    "Best Time to Buy And Sell Stock",
    "Longest Substring Without Repeating Characters",
    "Longest Repeating Character Replacement",
    "Permutation In String",
    "Minimum Window Substring",
    "Sliding Window Maximum",
    "Valid Parentheses",
    "Min Stack",
    "Evaluate Reverse Polish Notation",
    "Daily Temperatures",
    "Car Fleet",
    "Largest Rectangle In Histogram",
]

CS_QUESTIONS = [
# "String formatting in python",
# "Object-Oriented Programming in Python",
# "Python list operations and time complexity",
# "Python dictionary operations and time complexity",
# "Python string operations and time complexity",
# "python collections module, deque, defaultdict, Counter and their time complexities",
# "python bisect",
# "python heapq",
# "python itertools module",
# "python functools",
# "Stacks",
# "implement stacks in python",
# "convert decimal to n base",
# "Infix, Prefix, and Postfix Expressions, convertors and evaluators",
# "queues",
# "queues implementation in python",
# "deque implemention using common python data structures (dont use deque class directly)",
"Linked List, implementation of common operations (both iterative and recursive) and time complexity",
# "Doubly Linked List, implementation of common operations (both iterative and recursive) and time complexity",
# "Tower of Hanoi",
# "Dynamic programming",
# "Binary Search",
# "Hashing",
# "Implementing the Map Abstract Data Type",
# "Bubble, selection and insertion sort",
# "Merge sort",
# "quick sort",
]
