# Questions

QUESTIONS = [
    "Contains Duplicate",
    "Valid Anagram",
    "Two Sum",
    "Group Anagrams",
    "Top K Frequent Elements",
    "Encode and Decode Strings",
    "Product of Array Except Self",
    "Valid Sudoku",
    "Longest Consecutive Sequence",
    "Valid Palindrome",
    "Two Sum II Input Array Is Sorted",
    "3Sum",
    "Container With Most Water",
    "Trapping Rain Water",
    "Best Time to Buy And Sell Stock",
    "Longest Substring Without Repeating Characters",
    "Longest Repeating Character Replacement",
    "Permutation In String",
    "Minimum Window Substring",
    "Sliding Window Maximum",
    "Valid Parentheses",
    "Min Stack",
    "Evaluate Reverse Polish Notation",
    "Daily Temperatures",
    "Car Fleet",
    "Largest Rectangle In Histogram",
]

CS_QUESTIONS = [
# "String formatting in python",
# "Object-Oriented Programming in Python",
# "Python list operations and time complexity",
# "Python dictionary operations and time complexity",
# "Python string operations and time complexity",
# "python collections module, deque, defaultdict, Counter and their time complexities",
# "python bisect",
# "python heapq",
# "python itertools module",
# "python functools",
# "Stacks",
# "implement stacks in python",
# "convert decimal to n base",
# "Infix, Prefix, and Postfix Expressions, convertors and evaluators",
# "queues",
# "queues implementation in python",
# "deque implemention using common python data structures (dont use deque class directly)",
"Linked List, implementation of common operations (both iterative and recursive) and time complexity",
# "Doubly Linked List, implementation of common operations (both iterative and recursive) and time complexity",
# "Tower of Hanoi",
# "Dynamic programming",
# "Binary Search",
# "Hashing",
# "Implementing the Map Abstract Data Type",
# "Bubble, selection and insertion sort",
# "Merge sort",
# "quick sort",
]


PHYSICS_QUESTIONS = [
    "Dimensional Analysis",
    "Vector Algebra",
    "Vector Calculus",
    "Concepts of Tensors",
    "Linear ordinary differential equations of first order",
    # "Linear ordinary differential equations of second order",
    # "Special functions (Legendre functions)",
    # "Special functions (Hermite functions)",
    # "Special functions (Bessel functions)",
    # "Special functions (Laguerre functions)",
    # "Fourier series",
    # "Fourier transforms",
    # "Laplace transforms",
    # "Partial differential equations (Laplace equation)",
    # "Partial differential equations (Wave equation)",
    # "Partial differential equations (Heat equation)",
    # "Elementary probability theory",
    # "Random variables",
    # "Binomial distribution",
    # "Poisson distribution",
    # "Normal distribution",
    # "Dynamics of particle",
    # "Dynamics of system of particles",
    # "Conservation of linear momentum",
    # "Conservation of angular momentum",
    # "Conservation of energy",
    # "Central force motion",
    # "Reduction of two body central force problem",
    # "Planets and satellite motion",
    # "Communication satellite",
    # "D’Alembert’s principle",
    # "Generalised coordinates",
    # "Lagrangian equations",
    # "Cyclic coordinates",
    # "Hamiltonian formulation",
    # "Canonical transformation",
    # "Poisson brackets",
    # "Hamilton–Jacobi theory",
    # "Rigid body motion",
    # "Relative motion",
    # "Galilean transformation",
    # "Special theory of relativity",
    # "Lorentz transformation",
    # "Length contraction",
    # "Time dilation",
    # "Velocity addition",
    # "Simultaneity",
    # "Mass-energy equivalence",
    # "Doppler effect in light",
    # "Elastic behaviour of loaded wire",
    # "Elastic constants",
    # "Torsion of cylinder",
    # "Bending of beams",
    # "Cantilever",
    # "Surface tension",
    # "Surface energy",
    # "Angle of contact",
    # "Capillarity",
    # "Excess pressure",
    # "Ideal fluid",
    # "Hydrodynamic equations",
    # "Viscous force (Newton’s law)",
    # "Viscous force (Poiseuille’s law)",
    # "Laws of thermodynamics",
    # "Thermodynamical scales",
    # "Thermodynamical potentials",
    # "Maxwell’s relations",
    # "Clausius–Clapeyron equation",
    # "Heat engine",
    # "Carnot cycle",
    # "Refrigerator",
    # "Transport phenomenon of gases",
    # "Kinetic theory of gases",
    # "Equipartition of energy",
    # "Viscosity",
    # "Black body radiation",
    # "Kirchhoff’s laws",
    # "Planck’s distribution law",
    # "Stefan’s law",
    # "Wien’s law",
    # "Phase space",
    # "Microstates and macrostates",
    # "Micro-canonical ensemble",
    # "Canonical ensemble",
    # "Grand canonical ensemble",
    # "Partition functions",
    # "Free energy",
    # "First order phase transitions",
    # "Second order phase transitions",
    # "Classical statistics",
    # "Quantum statistics",
    # "Ideal Fermi gas",
    # "Ideal Bose gas",
    # "Bose-Einstein condensation",
    # "Thermodynamic entropy",
    # "Statistical entropy",
    # "Gibb’s paradox",
    # "Free electrons in metals",
    # "Wave-particle duality",
    # "Matter waves",
    # "Uncertainty principle",
    # "Photoelectric effect",
    # "Compton effect",
    # "Davisson-Germer experiment",
    # "Wave packets",
    # "Time-dependent Schrödinger equation",
    # "Time-independent Schrödinger equation",
    # "Physical significance of wave function",
    # "Normalization",
    # "Orthogonality",
    # "Eigenvalues",
    # "Eigenfunctions",
    # "Particle in a box",
    # "Harmonic oscillator",
    # "Tunnelling through a barrier",
    # "Motion in a central potential",
    # "Orbital angular momentum",
    # "Angular momentum algebra",
    # "Hydrogen atom",
    # "Spin-orbit coupling",
    # "Fine structure",
    # "Time-independent perturbation theory",
    # "Time-dependent perturbation theory",
    # "Fermi’s Golden rule",
    # "Elementary theory of scattering",
    # "Phase shifts",
    # "Partial waves",
    # "Born approximation",
    # "Pauli’s exclusion principle",
    # "Spin-statistics connection",
    # "Bohr atomic model",
    # "Sommerfeld atomic model",
    # "Hydrogen-like atoms",
    # "Optical spectra",
    # "X-ray spectra",
    # "Moseley law",
    # "Vector atom model",
    # "Bohr magneton",
    # "Larmor frequency",
    # "Stern-Gerlach experiment",
    # "Quantum states of electron in atom",
    # "Spectrum of hydrogen",
    # "Spectrum of helium",
    # "Spectrum of alkali atoms",
    # "Relativistic correction of hydrogen energy levels",
    # "Hyperfine structure",
    # "Isotopic shift",
    # "Selection rules",
    # "Width of spectral lines",
    # "L-S coupling",
    # "J-J coupling",
    # "Lande g-factor",
    # "Zeeman effect (normal)",
    # "Zeeman effect (anomalous)",
    # "Paschen-Back effect",
    # "Stark effect",
    # "Electronic molecular spectra",
    # "Rotational molecular spectra",
    # "Vibrational molecular spectra",
    # "Raman effect",
    # "Phosphorescence",
    # "Electron spin resonance",
    # "Nuclear magnetic resonance",
    # "Spontaneous emission",
    # "Stimulated emission",
    # "Einstein A and B coefficients",
    # "Lasers",
    # "Optical pumping",
    # "Population inversion",
    # "Rate equations",
    # "Gauss’s law",
    # "Laplace equation",
    # "Poisson equation",
    # "Boundary value problems",
    # "Biot-Savart law",
    # "Ampere’s law",
    # "Electromagnetic induction",
    # "Conduction current",
    # "Displacement current",
    # "Maxwell’s equations in free space",
    # "Maxwell’s equations in linear isotropic media",
    # "Boundary conditions at interfaces",
    # "Scalar potential",
    # "Vector potential",
    # "Gauge transformations",
    # "Poynting theorem",
    # "Electromagnetic waves in free space",
    # "Electromagnetic waves in dielectrics",
    # "Electromagnetic waves in conductors",
    # "Transmission lines",
    # "Waveguides",
    # "Reflection",
    # "Refraction",
    # "Polarisation",
    # "Fresnel equations",
    # "Dispersion of electromagnetic waves",
    # "Dynamics of charged particle in EM field",
    # "Radiation from moving charges",
    # "Radiation from dipoles",
    # "Retarded potentials",
    # "Image formation",
    # "Cardinal points",
    # "Thick lenses",
    # "Thin lenses",
    # "Huygens eyepiece",
    # "Ramsden eyepiece",
    # "Telescopes",
    # "Microscopes",
    # "Defects of vision",
    # "Human eye",
    # "Camera",
    # "Theories of light",
    # "Interference of light",
    # "Young’s double slit experiment",
    # "Biprism",
    # "Colours in thin films",
    # "Newton’s rings",
    # "Michelson interferometer",
    # "Fabry-Perot interferometer",
    # "Fresnel diffraction",
    # "Fraunhofer diffraction",
    # "Zone plate",
    # "Single slit diffraction",
    # "Multiple slit diffraction",
    # "Plane grating",
    # "Resolving power",
    # "Resolution criteria",
    # "Unpolarized light",
    # "Polarized light",
    # "Polarization of light",
    # "Double refraction",
    # "Malus law",
    # "Nicol prism",
    # "Half wave plate",
    # "Quarter wave plate",
    # "Optical rotation",
    # "Polarimeters",
    # "Ruby laser",
    # "He-Ne laser",
    # "Semiconductor laser",
    # "Applications of lasers",
    # "Holography",
    # "Intrinsic semiconductors",
    # "Extrinsic semiconductors",
    # "P-N junction",
    # "Diode",
    # "Clipping circuits",
    # "Clamping circuits",
    # "Zener diode",
    # "Regulated power supply",
    # "Common cathode amplifier",
    # "Common base amplifier",
    # "Common emitter amplifier",
    # "Transistor as a switch",
    # "Feedback in amplifiers",
    # "Oscillators",
    # "FET",
    # "MOSFET",
    # "Operational amplifier",
    # "Analog signals",
    # "Digital signals",
    # "Digital integrated circuits",
    # "Logic gates",
    # "NAND gate",
    # "NOR gate",
    # "XOR gate",
    # "Half adder",
    # "Full adder",
    # "Truth tables",
    # "Venn diagram",
    # "Boolean functions",
    # "Boolean theorems",
    # "Microprocessors",
    # "Flip-flops",
    # "LED",
    # "Photo detectors",
    # "Photo transistors",
    # "Solar cells",
    # "Mean value of AC",
    # "RMS value of AC",
    # "LR resonance",
    # "CR resonance",
    # "LCR resonance",
    # "Quality factor",
    # "Crystal structure",
    # "Miller indices",
    # "Bravais lattice",
    # "Diffraction",
    # "Structure factor",
    # "Bonding of solids",
    # "Elastic properties",
    # "Phonons",
    # "Lattice specific heat",
    # "Free electron theory",
    # "Electron specific heat",
    # "Einstein model",
    # "Debye model",
    # "Response phenomenon",
    # "Relaxation phenomenon",
    # "Drude model",
    # "Electrical conductivity",
    # "Thermal conductivity",
    # "Boltzmann transport equation",
    # "Sommerfeld theory",
    # "Matthiessen’s rule",
    # "Hall effect",
    # "Thermoelectric power",
    # "Atomic magnetism",
    # "Diamagnetism",
    # "Paramagnetism",
    # "Ferromagnetism",
    # "Electron motion in periodic potential",
    # "Band theory of metals",
    # "Kronig-Penney model",
    # "Effective mass",
    # "Holes",
    # "Insulators",
    # "Semiconductors",
    # "Superconductivity",
    # "Type I superconductors",
    # "Type II superconductors",
    # "BCS theory",
    # "DC Josephson effect",
    # "AC Josephson effect",
    # "Law of mass action",
    # "Impurity conductivity",
    # "Photoconductivity",
    # "Photoluminescence",
    # "Nuclear size",
    # "Nuclear shape",
    # "Charge distribution",
    # "Nuclear spin",
    # "Parity",
    # "Binding energy",
    # "Binding energy per nucleon",
    # "Semi-empirical mass formula",
    # "Nuclear forces",
    # "Charge independence of nuclear forces",
    # "Charge symmetry of nuclear forces",
    # "Deuteron problem",
    # "Radioactivity",
    # "Age of rocks",
    # "Carbon dating",
    # "Theory of beta decay",
    # "Selection rules",
    # "Nuclear reactions",
    # "Compound nucleus",
    # "Direct reactions",
    # "Nuclear fission",
    # "Nuclear fusion",
    # "Controlled chain reactions",
    # "Uncontrolled chain reactions",
    # "Thermonuclear reactions",
    # "Nuclear reactors",
    # "Liquid drop model",
    # "Shell model",
    # "Collective model",
    # "Ionization chamber",
    # "G.M. counter",
    # "Semiconductor detector",
    # "Fundamental forces",
    # "Classification of elementary particles",
    # "Quantum numbers",
    # "Quark model",
    # "Baryons",
    # "Leptons",
    # "Mesons",
    # "Conservation laws",
    # "Parity non-conservation",
    # "Particle accelerators"
    ]
