import { resolveProviderModel, callLLM } from './providers.js';
import { addPipelineStep } from './database.js';
import { resolvePrompts } from './prompts.js';

/**
 * Executes Stage 1 of the pipeline: Parallel Generation.
 * For a given chunk/topic, queries all configured generation models in parallel.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic (e.g. topic name).
 * @param {string} params.content Source text content or topic description.
 * @param {string} params.deckPath The parsed double-colon deck path.
 * @param {string} params.cardType Layout format ('standard' or 'mcq').
 * @param {string} params.subject Explicit subject name passed to the pipeline.
 * @param {Object} params.prompts Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @returns {Promise<Array<Object>>} Array of model responses.
 */
export async function runStage1({
  runId,
  questionId,
  content,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
}) {
  const models = config.pipeline?.generation?.models || [];
  if (models.length === 0) {
    throw new Error('No generation models configured in config.pipeline.generation.models');
  }

  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const systemPrompt = resolvedPrompts.generation;
  const userPrompt = `Source Content:\n${content}`;

  // Construct user messages for LLM processing
  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  // Maps each configured model to an asynchronous generation promise.
  // These promises execute concurrently when resolved with Promise.all.
  const promises = models.map(async (modelString) => {
    // Resolve model identifier into provider name and specific model name
    const { provider, model } = resolveProviderModel(modelString);

    // Call the LLM provider. callLLM handles concurrency throttling,
    // network timeouts, exponential backoff retries, and API key cycling.
    const output = await callLLM({
      provider,
      model,
      messages,
      config,
      keys,
      clients,
      throttledFetch,
    });

    // Log the completed step to the pipeline_steps table.
    // This allows run auditing and run resumption (skipping already completed queries on crash).
    addPipelineStep({
      runId,
      questionId,
      stage: 'generation',
      provider,
      model,
      inputData: JSON.stringify(messages),
      outputData: output,
    });

    return { provider, model, output };
  });

  // Await execution of all concurrent model requests
  return Promise.all(promises);
}

/**
 * Executes Stage 2 of the pipeline: Frontier Synthesis.
 * Consolidates multiple lists of raw text flashcards generated by different models.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic (e.g. topic name).
 * @param {Array<Object>} params.stage1Results Outputs from Stage 1.
 * @param {string} [params.cardType='standard'] Layout format ('standard' or 'mcq').
 * @param {string} [params.subject=''] Explicit subject name passed to the pipeline.
 * @param {Object} [params.prompts={}] Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @returns {Promise<string>} Consolidate synthesized text.
 */
export async function runStage2({
  runId,
  questionId,
  stage1Results,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
}) {
  // Retrieve synthesis model specification (e.g. "openai/gpt-4o") from system configuration.
  const modelString = config?.pipeline?.synthesis?.model;
  if (!modelString) {
    throw new Error('No synthesis model configured in config.pipeline.synthesis.model');
  }

  // Synthesis requires at least one raw card list generated from Stage 1.
  if (!Array.isArray(stage1Results) || stage1Results.length === 0) {
    throw new Error('No Stage 1 results provided');
  }

  // Combine parallel generation outputs from Stage 1.
  // We format each with explicit boundaries showing its provider/model source.
  // This informs the frontier synthesis model exactly where each set of flashcards came from,
  // allowing it to intelligently cross-reference, merge, and resolve duplicates.
  const combinedContent = stage1Results
    .map((res) => {
      if (!res || typeof res.output !== 'string') {
        throw new Error('Stage 1 result item is missing a valid string output');
      }
      const providerVal = res.provider || 'unknown-provider';
      const modelVal = res.model || 'unknown-model';
      return `--- Provider: ${providerVal}, Model: ${modelVal} ---\n${res.output}`;
    })
    .join('\n\n');

  // Dynamically resolve Stage 2 prompts: uses global templates, custom YAML prompts,
  // and subject-specific combiners if defined in prompts.yaml.
  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const systemPrompt = resolvedPrompts.synthesis;
  const userPrompt = `Flashcard lists to consolidate:\n\n${combinedContent}`;

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  // Resolve the string configuration ("provider/model") to discrete fields.
  const { provider, model } = resolveProviderModel(modelString);

  // Invoke the synthesis model through the unified provider client.
  // Throttling, timeouts, key-rotation, and rate-limit backoffs are managed inside callLLM.
  const output = await callLLM({
    provider,
    model,
    messages,
    config,
    keys,
    clients,
    throttledFetch,
  });

  // Log the completed synthesis step in the pipeline_steps table.
  // This is vital for:
  // 1. Audit trail logging (inspecting what the model consolidated).
  // 2. Resume feature (allowing users to restart interrupted runs from the last successful stage).
  addPipelineStep({
    runId,
    questionId,
    stage: 'synthesis',
    provider,
    model,
    inputData: JSON.stringify(messages),
    outputData: output,
  });

  return output;
}
