import Ajv from 'ajv';
import { z } from 'zod';
import { resolveProviderModel, callLLM } from './providers.js';
import { addPipelineStep, upsertQuestionEntry } from './database.js';
import { resolvePrompts } from './prompts.js';

/**
 * Executes Stage 1 of the pipeline: Parallel Generation.
 * For a given chunk/topic, queries all configured generation models in parallel.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic (e.g. topic name).
 * @param {string} [params.topicName] Optional original topic name.
 * @param {string} params.content Source text content or topic description.
 * @param {string} params.deckPath The parsed double-colon deck path.
 * @param {string} params.cardType Layout format ('standard' or 'mcq').
 * @param {string} params.subject Explicit subject name passed to the pipeline.
 * @param {Object} params.prompts Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @returns {Promise<Array<Object>>} Array of model responses.
 */
export async function runStage1({
  runId,
  questionId,
  topicName,
  content,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
}) {
  const models = config.pipeline?.generation?.models || [];
  if (models.length === 0) {
    throw new Error('No generation models configured in config.pipeline.generation.models');
  }

  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const systemPrompt = resolvedPrompts.generation;

  let userPrompt;
  if (content && content.trim().length > 0) {
    userPrompt = `Source Content:\n${content}`;
  } else {
    const target = topicName || questionId.replace(/_/g, ' ');
    userPrompt = `Please generate comprehensive flashcards for the following topic: ${target}`;
  }

  // Construct user messages for LLM processing
  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  // Maps each configured model to an asynchronous generation promise.
  // These promises execute concurrently when resolved with Promise.all.
  const promises = models.map(async (modelString) => {
    // Resolve model identifier into provider name and specific model name
    const { provider, model } = resolveProviderModel(modelString);

    // Call the LLM provider. callLLM handles concurrency throttling,
    // network timeouts, exponential backoff retries, and API key cycling.
    const output = await callLLM({
      provider,
      model,
      messages,
      config,
      keys,
      clients,
      throttledFetch,
    });

    // Log the completed step to the pipeline_steps table.
    // This allows run auditing and run resumption (skipping already completed queries on crash).
    addPipelineStep({
      runId,
      questionId,
      stage: 'generation',
      provider,
      model,
      inputData: JSON.stringify(messages),
      outputData: output,
    });

    upsertQuestionEntry({
      runId,
      questionId,
      currentStage: 'generation',
      inputContent: content,
      latestPrompt: JSON.stringify(messages),
      latestResponse: output,
    });

    return { provider, model, output };
  });

  // Await execution of all concurrent model requests
  return Promise.all(promises);
}

/**
 * Executes Stage 2 of the pipeline: Frontier Synthesis.
 * Consolidates multiple lists of raw text flashcards generated by different models.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic (e.g. topic name).
 * @param {Array<Object>} params.stage1Results Outputs from Stage 1.
 * @param {string} [params.cardType='standard'] Layout format ('standard' or 'mcq').
 * @param {string} [params.subject=''] Explicit subject name passed to the pipeline.
 * @param {Object} [params.prompts={}] Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @returns {Promise<string>} Consolidate synthesized text.
 */
export async function runStage2({
  runId,
  questionId,
  stage1Results,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
}) {
  // Retrieve synthesis model specification (e.g. "openai/gpt-4o") from system configuration.
  const modelString = config?.pipeline?.synthesis?.model;
  if (!modelString) {
    throw new Error('No synthesis model configured in config.pipeline.synthesis.model');
  }

  // Synthesis requires at least one raw card list generated from Stage 1.
  if (!Array.isArray(stage1Results) || stage1Results.length === 0) {
    throw new Error('No Stage 1 results provided');
  }

  // Combine parallel generation outputs from Stage 1.
  // We format each with explicit boundaries showing its provider/model source.
  // This informs the frontier synthesis model exactly where each set of flashcards came from,
  // allowing it to intelligently cross-reference, merge, and resolve duplicates.
  const combinedContent = stage1Results
    .map((res) => {
      if (!res || typeof res.output !== 'string') {
        throw new Error('Stage 1 result item is missing a valid string output');
      }
      const providerVal = res.provider || 'unknown-provider';
      const modelVal = res.model || 'unknown-model';
      return `--- Provider: ${providerVal}, Model: ${modelVal} ---\n${res.output}`;
    })
    .join('\n\n');

  // Dynamically resolve Stage 2 prompts: uses global templates, custom YAML prompts,
  // and subject-specific combiners if defined in prompts.yaml.
  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const systemPrompt = resolvedPrompts.synthesis;
  const userPrompt = `Flashcard lists to consolidate:\n\n${combinedContent}`;

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  // Resolve the string configuration ("provider/model") to discrete fields.
  const { provider, model } = resolveProviderModel(modelString);

  // Invoke the synthesis model through the unified provider client.
  // Throttling, timeouts, key-rotation, and rate-limit backoffs are managed inside callLLM.
  const output = await callLLM({
    provider,
    model,
    messages,
    config,
    keys,
    clients,
    throttledFetch,
  });

  // Log the completed synthesis step in the pipeline_steps table.
  // This is vital for:
  // 1. Audit trail logging (inspecting what the model consolidated).
  // 2. Resume feature (allowing users to restart interrupted runs from the last successful stage).
  addPipelineStep({
    runId,
    questionId,
    stage: 'synthesis',
    provider,
    model,
    inputData: JSON.stringify(messages),
    outputData: output,
  });

  upsertQuestionEntry({
    runId,
    questionId,
    currentStage: 'synthesis',
    latestPrompt: JSON.stringify(messages),
    latestResponse: output,
  });

  return output;
}
/**
 * Recursively removes keys with null or undefined values from an object or array.
 * This is necessary because OpenAI's Structured Outputs (enforced via Zod schema)
 * require all properties to be present in the schema, making optional fields nullable.
 * However, the legacy AJV JSON schema expects optional properties (like back, options,
 * correct_answer for Cloze or MCQ cards) to be completely absent from the object
 * rather than having null values, otherwise it triggers validation errors.
 *
 * @param {*} obj - The input object, array, or primitive.
 * @returns {*} The input with all null and undefined fields stripped out.
 */
export function removeNullValues(obj) {
  if (Array.isArray(obj)) {
    return obj.map(removeNullValues);
  } if (obj !== null && typeof obj === 'object') {
    const newObj = {};
    for (const key of Object.keys(obj)) {
      if (obj[key] !== null && obj[key] !== undefined) {
        newObj[key] = removeNullValues(obj[key]);
      }
    }
    return newObj;
  }
  return obj;
}

// Zod schemas defining the structured output format for flashcards.
// These mirror CARD_JSON_SCHEMA, but mark optional fields as nullable()
// to satisfy OpenAI's Structured Outputs requirement that all properties are required.

const CardItemSchema = z.object({
  card_format: z.enum(['Basic', 'Cloze', 'MCQ']).describe('The structural layout of the card in Anki.'),
  card_type: z.enum(['Concept', 'Code', 'Procedure', 'Syntax', 'Behavior', 'Constraint', 'ErrorHandling', 'TradeOff']).describe('Pedagogical tag for sorting and styled headers.'),
  tags: z.array(z.string().regex(/^[A-Za-z0-9-_/]+$/)).describe('Alphanumeric, hyphen, underscore, and slash tags (no spaces allowed).'),
  front: z.string().describe('Front/question side of the card, or statement with {{c1::hidden text}} syntax for Cloze.'),
  back: z.string().nullable().describe('Short, punchy answer. Required for Basic card format; prohibited in MCQ or Cloze.'),
  options: z.array(z.string()).min(2).max(4).nullable()
    .describe('2 to 4 choices. Required only for MCQ.'),
  correct_answer: z.enum(['A', 'B', 'C', 'D']).nullable().describe('Correct choice letter index. Required only for MCQ.'),
  explanation: z.string().describe('Detailed background explanation, code examples, or trade-offs shown on the back side of all card formats.'),
});

export const CARD_ZOD_SCHEMA = z.object({
  title: z.string().describe('Title of the concept, problem, or document section.'),
  topic: z.string().describe('Main category hierarchy or path.'),
  difficulty: z.enum(['Basic', 'Intermediate', 'Advanced']).describe('Standardized difficulty level for database sorting.'),
  cards: z.array(CardItemSchema),
});

export const CARD_JSON_SCHEMA = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    title: { type: 'string', description: 'Title of the concept, problem, or document section.' },
    topic: { type: 'string', description: 'Main category hierarchy or path.' },
    difficulty: {
      type: 'string',
      enum: ['Basic', 'Intermediate', 'Advanced'],
      description: 'Standardized difficulty level for database sorting.',
    },
    cards: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          card_format: {
            type: 'string',
            enum: ['Basic', 'Cloze', 'MCQ'],
            description: 'The structural layout of the card in Anki.',
          },
          card_type: {
            type: 'string',
            enum: ['Concept', 'Code', 'Procedure', 'Syntax', 'Behavior', 'Constraint', 'ErrorHandling', 'TradeOff'],
            description: 'Pedagogical tag for sorting and styled headers.',
          },
          tags: {
            type: 'array',
            items: { type: 'string', pattern: '^[A-Za-z0-9-_/]+$' },
            description: 'Alphanumeric, hyphen, underscore, and slash tags (no spaces allowed).',
          },
          front: { type: 'string', description: 'Front/question side of the card, or statement with {{c1::hidden text}} syntax for Cloze.' },
          back: { type: 'string', description: 'Short, punchy answer. Required for Basic card format; prohibited in MCQ or Cloze.' },
          options: {
            type: 'array',
            items: { type: 'string' },
            minItems: 2,
            maxItems: 4,
            description: '2 to 4 choices. Required only for MCQ.',
          },
          correct_answer: {
            type: 'string',
            enum: ['A', 'B', 'C', 'D'],
            description: 'Correct choice letter index. Required only for MCQ.',
          },
          explanation: {
            type: 'string',
            description: 'Detailed background explanation, code examples, or trade-offs shown on the back side of all card formats.',
          },
        },
        required: ['card_format', 'card_type', 'tags', 'explanation'],
        additionalProperties: false,
        oneOf: [
          {
            properties: {
              card_format: { const: 'Basic' },
              options: { not: {} },
              correct_answer: { not: {} },
            },
            required: ['front', 'back'],
          },
          {
            properties: {
              card_format: { const: 'Cloze' },
              front: { pattern: '\\{\\{c[0-9]+::' },
              back: { not: {} },
              options: { not: {} },
              correct_answer: { not: {} },
            },
            required: ['front'],
            description: 'front must contain at least one cloze deletion using {{c1::word}} syntax.',
          },
          {
            properties: {
              card_format: { const: 'MCQ' },
              back: { not: {} },
            },
            required: ['front', 'options', 'correct_answer'],
          },
        ],
        allOf: [
          {
            if: {
              properties: {
                card_format: { const: 'MCQ' },
                correct_answer: { const: 'C' },
              },
              required: ['card_format', 'correct_answer'],
            },
            then: {
              properties: {
                options: { minItems: 3 },
              },
            },
          },
          {
            if: {
              properties: {
                card_format: { const: 'MCQ' },
                correct_answer: { const: 'D' },
              },
              required: ['card_format', 'correct_answer'],
            },
            then: {
              properties: {
                options: { minItems: 4 },
              },
            },
          },
        ],
      },
    },
  },
  required: ['title', 'topic', 'difficulty', 'cards'],
  additionalProperties: false,
};

/**
 * Cleans markdown code block wraps from raw text returned by the LLM.
 *
 * @param {string} text Raw response.
 * @returns {string} Cleaned text.
 */
export function cleanJsonOutput(text) {
  if (typeof text !== 'string') return '';
  let cleaned = text.trim();

  // If the text already starts with a JSON object or array delimiter,
  // skip code-fence stripping. The regex below would incorrectly match
  // triple-backtick code blocks embedded *inside* JSON string values
  // (e.g. explanation fields containing ```javascript ... ```),
  // extracting inner code instead of the actual JSON object.
  if (!cleaned.startsWith('{') && !cleaned.startsWith('[')) {
    // Try to match the content inside a top-level markdown code fence
    // (with any word-based language identifier like json, javascript, etc.)
    const codeBlockMatch = cleaned.match(/```[a-z]*\s*([\s\S]*?)\s*```/i);
    if (codeBlockMatch) {
      cleaned = codeBlockMatch[1].trim();
    }
  }

  return cleaned;
}

/**
 * Extracts question/front strings from Stage 2 raw text consolidated lists.
 *
 * @param {string} text Raw consolidated list.
 * @returns {string[]} List of question texts.
 */
export function parseStage2Questions(text) {
  if (typeof text !== 'string') return [];
  const lines = text.split('\n');
  const questions = [];
  for (const line of lines) {
    const trimmed = line.trim();
    // Match lines starting with "Front:", "Q:", or "Question:"
    // with optional bold markers or "Card X" prefix
    const regexPattern = '^(?:\\*\\*|)?(?:Card\\s*\\d+\\s*:?\\s*)?'
      + '(?:Front|Q(?:uestion)?)\\s*:\\s*(?:\\*\\*|)?(.*)';
    const questionRegex = new RegExp(regexPattern, 'i');
    const match = trimmed.match(questionRegex);
    if (match) {
      let qText = match[1].trim();
      qText = qText.replace(/\*\*$/, '').trim();
      if (qText) {
        questions.push(qText);
      }
    }
  }
  return questions;
}

/**
 * Audit checks that every Stage 2 question has a corresponding representation
 * in the Stage 3 card objects.
 *
 * @param {string[]} stage2Questions List of questions parsed from Stage 2.
 * @param {Array<Object>} stage3Cards List of cards from Stage 3 JSON.
 * @returns {string[]} Missing questions.
 */
export function verifyContentLoss(stage2Questions, stage3Cards) {
  const missingQuestions = [];
  if (!Array.isArray(stage3Cards)) {
    return [...stage2Questions];
  }

  for (const s2Q of stage2Questions) {
    const normalizedS2 = s2Q.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!normalizedS2) continue;

    let found = false;
    for (const card of stage3Cards) {
      if (card && typeof card.front === 'string') {
        const normalizedS3 = card.front.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (normalizedS3.includes(normalizedS2) || normalizedS2.includes(normalizedS3)) {
          found = true;
          break;
        }
      }
    }
    if (!found) {
      missingQuestions.push(s2Q);
    }
  }
  return missingQuestions;
}

/**
 * Executes Stage 3 of the pipeline: AJV Schema Enforcement.
 * Enforces schema compliance and translates consolidated text from Stage 2
 * into valid polymorphic JSON cards.
 * Uses an AJV compiler for validation and run a recovery re-prompt loop on failures.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic.
 * @param {string} params.synthesisResult Stage 2 consolidated text output.
 * @param {string} [params.cardType='standard'] Layout format ('standard' or 'mcq').
 * @param {string} [params.subject=''] Explicit subject name passed to the pipeline.
 * @param {Object} [params.prompts={}] Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @param {number} [params.maxEnforcementRetries=5] Maximum recovery re-prompts on failures.
 * @returns {Promise<Object>} The conforming parsed JSON cards object.
 */
export async function runStage3({
  runId,
  questionId,
  synthesisResult,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
  maxEnforcementRetries = 5,
}) {
  if (typeof synthesisResult !== 'string' || !synthesisResult.trim()) {
    throw new Error('Stage 2 synthesis result is missing or empty');
  }

  // Retrieve schema enforcement model config
  const modelString = config?.pipeline?.schema_enforcement?.model;
  if (!modelString) {
    throw new Error('No schema enforcement model configured in config.pipeline.schema_enforcement.model');
  }

  const { provider, model } = resolveProviderModel(modelString);

  // Resolve Stage 3 prompts
  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const enforcementBase = resolvedPrompts.enforcement;

  // Inject target JSON Schema to guide enforcement
  const systemPrompt = `${enforcementBase}\n\nYou must output a JSON object conforming strictly to this JSON Schema:\n${JSON.stringify(CARD_JSON_SCHEMA, null, 2)}\n\nIMPORTANT: Output ONLY the raw JSON string. Do NOT wrap the JSON in markdown code blocks or backticks (e.g. do NOT use \`\`\`json ... \`\`\`).`;

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: `Consolidated Text Flashcard List:\n\n${synthesisResult}` },
  ];

  const ajv = new Ajv({ allErrors: true, strict: false });
  const validate = ajv.compile(CARD_JSON_SCHEMA);

  const stage2Questions = parseStage2Questions(synthesisResult);

  let attempt = 0;
  let lastErrorMsg = '';

  while (attempt < maxEnforcementRetries) {
    attempt++;
    const rawOutput = await callLLM({
      provider,
      model,
      messages,
      schema: CARD_ZOD_SCHEMA,
      config,
      keys,
      clients,
      throttledFetch,
    });

    const cleanedOutput = cleanJsonOutput(rawOutput);
    let jsonObj;
    const errorsList = [];

    // 1. JSON Parsing Check
    try {
      jsonObj = JSON.parse(cleanedOutput);
      if (jsonObj) {
        jsonObj = removeNullValues(jsonObj);
      }
    } catch (parseError) {
      errorsList.push(`JSON Parsing Error: ${parseError.message}`);
    }

    // 2. AJV Validation Check
    if (jsonObj) {
      const valid = validate(jsonObj);
      if (!valid) {
        const schemaErrors = validate.errors.map(
          (err) => `${err.instancePath || '/'}: ${err.message} (${JSON.stringify(err.params)})`,
        );
        errorsList.push(...schemaErrors);
      }
    }

    // 3. Content Loss Audit Check
    if (jsonObj) {
      const cards = jsonObj.cards || [];
      const missing = verifyContentLoss(stage2Questions, cards);
      if (missing.length > 0) {
        errorsList.push(
          `Content Loss Audit Error: The following questions from Stage 2 are missing in the Stage 3 JSON cards array:\n${
            missing.map((q) => `- ${q}`).join('\n')}`,
        );
      }
    }

    if (errorsList.length === 0) {
      // Success! Log the trace to pipeline_steps and return the conforming object
      addPipelineStep({
        runId,
        questionId,
        stage: 'enforcement',
        provider,
        model,
        inputData: JSON.stringify(messages),
        outputData: rawOutput,
      });

      upsertQuestionEntry({
        runId,
        questionId,
        currentStage: 'enforcement',
        latestPrompt: JSON.stringify(messages),
        latestResponse: rawOutput,
      });

      return jsonObj;
    }

    // Log failed attempt to pipeline_steps and run_questions for auditing/debugging
    const errorString = errorsList.join('\n');
    addPipelineStep({
      runId,
      questionId,
      stage: 'enforcement',
      provider,
      model,
      inputData: JSON.stringify(messages),
      outputData: rawOutput,
      status: 'failed',
      errors: errorString,
    });

    upsertQuestionEntry({
      runId,
      questionId,
      currentStage: 'synthesis', // Keep as synthesis so resumption knows it is not fully completed
      latestPrompt: JSON.stringify(messages),
      latestResponse: rawOutput,
      errors: errorString,
    });

    // Failed validation/audit: prepare feedback and append history for retry
    lastErrorMsg = errorsList.join('\n');
    messages.push({ role: 'assistant', content: rawOutput });
    messages.push({
      role: 'user',
      content: `Your previous output did not conform to the schema or failed the Content Loss Audit. Please fix the following errors and output the entire, corrected JSON matching the schema:\n\n${lastErrorMsg}`,
    });
  }

  throw new Error(
    `Stage 3 Schema Enforcement failed after ${maxEnforcementRetries} attempts.\nLast Errors:\n${lastErrorMsg}`,
  );
}
