import { z } from 'zod';
import pLimit from 'p-limit';
import { resolveProviderModel, callLLM } from './providers.js';
import { addPipelineStep, upsertQuestionEntry } from './database.js';
import { resolvePrompts, CARD_JSON_SCHEMA } from './prompts.js';
import { getLogger } from './logger.js';

const logger = getLogger(['stages']);

/**
 * Executes Stage 1 of the pipeline: Parallel Generation.
 * For a given chunk/topic, queries all configured generation models in parallel.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic (e.g. topic name).
 * @param {string} [params.topicName] Optional original topic name.
 * @param {string} params.content Source text content or topic description.
 * @param {string} params.deckPath The parsed double-colon deck path.
 * @param {string} params.cardType Layout format ('standard' or 'mcq').
 * @param {string} params.subject Explicit subject name passed to the pipeline.
 * @param {Object} params.prompts Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @returns {Promise<Array<Object>>} Array of model responses.
 */
export async function runStage1({
  runId,
  questionId,
  topicName,
  content,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
}) {
  const models = config.pipeline?.generation?.models || [];
  if (models.length === 0) {
    throw new Error('No generation models configured in config.pipeline.generation.models');
  }

  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const systemPrompt = resolvedPrompts.generation;

  let userPrompt;
  if (content && content.trim().length > 0) {
    userPrompt = `Source Content:\n${content}`;
  } else {
    const target = topicName || questionId.replace(/_/g, ' ');
    userPrompt = `Please generate comprehensive flashcards for the following topic: ${target}`;
  }

  // Construct user messages for LLM processing
  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  // Retrieve model_concurrency configuration. A value of 0 (or undefined)
  // indicates unlimited concurrency (meaning all generation models run in parallel).
  // Handles invalid, negative, or non-numeric values defensively by falling back to 0 (unlimited).
  let modelConcurrency = config.global?.model_concurrency;
  if (typeof modelConcurrency !== 'number' || modelConcurrency < 0 || Number.isNaN(modelConcurrency)) {
    modelConcurrency = 0;
  }
  const limit = modelConcurrency > 0 ? pLimit(modelConcurrency) : null;

  logger.debug`Starting Stage 1 (Parallel Generation) for question ID: ${questionId} using ${models.length} model(s)`;

  // Maps each configured model to an asynchronous generation promise.
  // These promises execute concurrently up to the model_concurrency limit.
  const promises = models.map((modelString) => {
    const task = async () => {
      // Resolve model identifier into provider name and specific model name
      const { provider, model } = resolveProviderModel(modelString);

      logger.debug`Stage 1 parallel call started for model ${modelString} on question ${questionId}`;

      // Call the LLM provider. callLLM handles concurrency throttling,
      // network timeouts, exponential backoff retries, and API key cycling.
      const output = await callLLM({
        provider,
        model,
        messages,
        config,
        keys,
        clients,
        throttledFetch,
      });

      // Log the completed step to the pipeline_steps table.
      // This allows run auditing and run resumption (skipping already completed queries on crash).
      addPipelineStep({
        runId,
        questionId,
        stage: 'generation',
        provider,
        model,
        inputData: JSON.stringify(messages),
        outputData: output,
      });

      upsertQuestionEntry({
        runId,
        questionId,
        currentStage: 'generation',
        inputContent: content,
        latestPrompt: JSON.stringify(messages),
        latestResponse: output,
      });

      logger.debug`Stage 1 call finished for model ${modelString} (response length: ${output.length} chars)`;

      return { provider, model, output };
    };

    return limit ? limit(task) : task();
  });

  // Await execution of all concurrent model requests
  return Promise.all(promises);
}

/**
 * Executes Stage 2 of the pipeline: Frontier Synthesis.
 * Consolidates multiple lists of raw text flashcards generated by different models.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic (e.g. topic name).
 * @param {Array<Object>} params.stage1Results Outputs from Stage 1.
 * @param {string} [params.cardType='standard'] Layout format ('standard' or 'mcq').
 * @param {string} [params.subject=''] Explicit subject name passed to the pipeline.
 * @param {Object} [params.prompts={}] Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @returns {Promise<string>} Consolidate synthesized text.
 */
export async function runStage2({
  runId,
  questionId,
  stage1Results,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
}) {
  // Retrieve synthesis model specification (e.g. "openai/gpt-4o") from system configuration.
  const modelString = config?.pipeline?.synthesis?.model;
  if (!modelString) {
    throw new Error('No synthesis model configured in config.pipeline.synthesis.model');
  }

  // Synthesis requires at least one raw card list generated from Stage 1.
  if (!Array.isArray(stage1Results) || stage1Results.length === 0) {
    throw new Error('No Stage 1 results provided');
  }

  // Combine parallel generation outputs from Stage 1.
  // We format each with explicit boundaries showing its provider/model source.
  // This informs the frontier synthesis model exactly where each set of flashcards came from,
  // allowing it to intelligently cross-reference, merge, and resolve duplicates.
  const combinedContent = stage1Results
    .map((res) => {
      if (!res || typeof res.output !== 'string') {
        throw new Error('Stage 1 result item is missing a valid string output');
      }
      const providerVal = res.provider || 'unknown-provider';
      const modelVal = res.model || 'unknown-model';
      return `--- Provider: ${providerVal}, Model: ${modelVal} ---\n${res.output}`;
    })
    .join('\n\n');

  // Dynamically resolve Stage 2 prompts: uses global templates, custom YAML prompts,
  // and subject-specific combiners if defined in prompts.yaml.
  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const systemPrompt = resolvedPrompts.synthesis;
  const userPrompt = `Flashcard lists to consolidate:\n\n${combinedContent}`;

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  // Resolve the string configuration ("provider/model") to discrete fields.
  const { provider, model } = resolveProviderModel(modelString);

  logger.debug`Starting Stage 2 (Frontier Synthesis) for ${questionId} using model ${modelString}. Input length: ${combinedContent.length} chars.`;

  // Invoke the synthesis model through the unified provider client.
  // Throttling, timeouts, key-rotation, and rate-limit backoffs are managed inside callLLM.
  const output = await callLLM({
    provider,
    model,
    messages,
    config,
    keys,
    clients,
    throttledFetch,
  });

  // Log the completed synthesis step in the pipeline_steps table.
  // This is vital for:
  // 1. Audit trail logging (inspecting what the model consolidated).
  // 2. Resume feature (allowing users to restart interrupted runs from the last successful stage).
  addPipelineStep({
    runId,
    questionId,
    stage: 'synthesis',
    provider,
    model,
    inputData: JSON.stringify(messages),
    outputData: output,
  });

  upsertQuestionEntry({
    runId,
    questionId,
    currentStage: 'synthesis',
    latestPrompt: JSON.stringify(messages),
    latestResponse: output,
  });

  logger.debug`Stage 2 synthesis finished for ${questionId}. Output length: ${output.length} chars.`;

  return output;
}
/**
 * Recursively removes keys with null or undefined values from an object or array.
 * This is necessary because OpenAI's Structured Outputs (enforced via Zod schema)
 * require all properties to be present in the schema, making optional fields nullable.
 * However, the legacy AJV JSON schema expects optional properties (like back, options,
 * correct_answer for Cloze or MCQ cards) to be completely absent from the object
 * rather than having null values, otherwise it triggers validation errors.
 *
 * @param {*} obj - The input object, array, or primitive.
 * @returns {*} The input with all null and undefined fields stripped out.
 */
export function removeNullValues(obj) {
  if (Array.isArray(obj)) {
    return obj.map(removeNullValues);
  } if (obj !== null && typeof obj === 'object') {
    const newObj = {};
    for (const key of Object.keys(obj)) {
      if (obj[key] !== null && obj[key] !== undefined) {
        newObj[key] = removeNullValues(obj[key]);
      }
    }
    return newObj;
  }
  return obj;
}

/**
 * Normalizes the parsed JSON object to heal/recover missing properties
 * (like title, tags, or topic) and prune incompatible properties (like
 * options and correct_answer for Basic/Cloze cards) before passing it
 * to Zod validation. This makes parsing resilient to LLM output variations.
 *
 * @param {Object} jsonObj The parsed JSON object.
 * @param {string} questionId Unique identifier for this chunk/topic.
 * @param {string} [subject] Explicit subject name.
 * @returns {Object} The normalized object.
 */
export function normalizeJsonObj(jsonObj, questionId, subject = '') {
  if (!jsonObj || typeof jsonObj !== 'object') {
    return jsonObj;
  }

  // 1. Fallbacks for root-level fields
  if (typeof jsonObj.title !== 'string' || !jsonObj.title.trim()) {
    const parts = questionId.split('::');
    const lastPart = parts[parts.length - 1];
    jsonObj.title = lastPart ? lastPart.replace(/_/g, ' ') : 'Flashcards';
  }

  if (typeof jsonObj.topic !== 'string' || !jsonObj.topic.trim()) {
    jsonObj.topic = questionId.replace(/::/g, '/');
  }

  const validDifficulties = ['Basic', 'Intermediate', 'Advanced'];
  if (!validDifficulties.includes(jsonObj.difficulty)) {
    jsonObj.difficulty = 'Intermediate';
  }

  // 2. Normalize and prune cards
  if (Array.isArray(jsonObj.cards)) {
    jsonObj.cards = jsonObj.cards.map((card) => {
      if (!card || typeof card !== 'object') return card;

      // Ensure tags is an array
      if (!Array.isArray(card.tags)) {
        card.tags = [];
      } else {
        card.tags = card.tags.filter(
          (t) => typeof t === 'string' && /^[A-Za-z0-9-_/]+$/.test(t),
        );
      }

      // Ensure card_type is valid, fallback to 'Concept'
      const validTypes = [
        'Concept',
        'Code',
        'Procedure',
        'Syntax',
        'Behavior',
        'Constraint',
        'ErrorHandling',
        'TradeOff',
      ];
      if (!validTypes.includes(card.card_type)) {
        card.card_type = 'Concept';
      }

      // Fallback card_format if missing or invalid
      if (!['Basic', 'Cloze', 'MCQ'].includes(card.card_format)) {
        if (card.options && card.correct_answer) {
          card.card_format = 'MCQ';
        } else if (card.front && /\{\{c[0-9]+::/.test(card.front)) {
          card.card_format = 'Cloze';
        } else {
          card.card_format = 'Basic';
        }
      }

      // Prune and format-specific normalization
      if (card.card_format === 'Basic') {
        delete card.options;
        delete card.correct_answer;
      } else if (card.card_format === 'Cloze') {
        delete card.back;
        delete card.options;
        delete card.correct_answer;
      } else if (card.card_format === 'MCQ') {
        delete card.back;
        if (!Array.isArray(card.options)) {
          card.options = ['Option A', 'Option B'];
        }
        if (!['A', 'B', 'C', 'D'].includes(card.correct_answer)) {
          card.correct_answer = 'A';
        }
      }

      return card;
    });
  }

  return jsonObj;
}

// Zod schemas defining the structured output format for flashcards.
// These mirror CARD_JSON_SCHEMA, but mark optional fields as nullable()
// to satisfy OpenAI's Structured Outputs requirement that all properties are required.

const CardItemSchema = z.object({
  card_format: z.enum(['Basic', 'Cloze', 'MCQ']).describe('The structural layout of the card in Anki.'),
  card_type: z.enum(['Concept', 'Code', 'Procedure', 'Syntax', 'Behavior', 'Constraint', 'ErrorHandling', 'TradeOff']).describe('Pedagogical tag for sorting and styled headers.'),
  tags: z.array(z.string().regex(/^[A-Za-z0-9-_/]+$/)).describe('Alphanumeric, hyphen, underscore, and slash tags (no spaces allowed).'),
  front: z.string().describe('Front/question side of the card, or statement with {{c1::hidden text}} syntax for Cloze.'),
  back: z.string().nullable().describe('Short, punchy answer. Required for Basic card format; prohibited in MCQ or Cloze.'),
  options: z.array(z.string()).min(2).max(4).nullable()
    .describe('2 to 4 choices. Required only for MCQ.'),
  correct_answer: z.enum(['A', 'B', 'C', 'D']).nullable().describe('Correct choice letter index. Required only for MCQ.'),
  explanation: z.string().describe('Detailed background explanation, code examples, or trade-offs shown on the back side of all card formats.'),
});

export const CARD_ZOD_SCHEMA = z.object({
  title: z.string().describe('Title of the concept, problem, or document section.'),
  topic: z.string().describe('Main category hierarchy or path.'),
  difficulty: z.enum(['Basic', 'Intermediate', 'Advanced']).describe('Standardized difficulty level for database sorting.'),
  cards: z.array(CardItemSchema),
});

// Strict Zod schema used to validate polymorphic card types after null/undefined values
// are stripped. It ensures format-specific properties are correctly structured.
const CardTypeSchema = z.enum([
  'Concept',
  'Code',
  'Procedure',
  'Syntax',
  'Behavior',
  'Constraint',
  'ErrorHandling',
  'TradeOff',
]);

const BasicCardSchema = z.object({
  card_format: z.literal('Basic'),
  card_type: CardTypeSchema,
  tags: z.array(z.string().regex(/^[A-Za-z0-9-_/]+$/)),
  front: z.string(),
  back: z.string(),
  explanation: z.string(),
}).strict();

const ClozeCardSchema = z.object({
  card_format: z.literal('Cloze'),
  card_type: CardTypeSchema,
  tags: z.array(z.string().regex(/^[A-Za-z0-9-_/]+$/)),
  front: z.string().refine((val) => /\{\{c[0-9]+::/.test(val), {
    message: 'front must contain at least one cloze deletion using {{c1::word}} syntax.',
  }),
  explanation: z.string(),
}).strict();

const MCQCardSchema = z.object({
  card_format: z.literal('MCQ'),
  card_type: CardTypeSchema,
  tags: z.array(z.string().regex(/^[A-Za-z0-9-_/]+$/)),
  front: z.string(),
  options: z.array(z.string()).min(2).max(4),
  correct_answer: z.enum(['A', 'B', 'C', 'D']),
  explanation: z.string(),
}).strict().superRefine((data, ctx) => {
  if (data.correct_answer === 'C' && (!data.options || data.options.length < 3)) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'options must NOT have fewer than 3 items when correct_answer is C',
      path: ['options'],
    });
  }
  if (data.correct_answer === 'D' && (!data.options || data.options.length < 4)) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'options must NOT have fewer than 4 items when correct_answer is D',
      path: ['options'],
    });
  }
});

const ValidationCardSchema = z.discriminatedUnion('card_format', [
  BasicCardSchema,
  ClozeCardSchema,
  MCQCardSchema,
]);

export const CARD_VALIDATION_SCHEMA = z.object({
  title: z.string(),
  topic: z.string(),
  difficulty: z.enum(['Basic', 'Intermediate', 'Advanced']),
  cards: z.array(ValidationCardSchema),
}).strict();

// CARD_JSON_SCHEMA was moved to src/prompts.js to separate prompt engineering schemas from logic.

/**
 * Cleans markdown code block wraps from raw text returned by the LLM.
 *
 * @param {string} text Raw response.
 * @returns {string} Cleaned text.
 */
export function cleanJsonOutput(text) {
  if (typeof text !== 'string') return '';
  let cleaned = text.trim();

  // If the text already starts with a JSON object or array delimiter,
  // skip code-fence stripping. The regex below would incorrectly match
  // triple-backtick code blocks embedded *inside* JSON string values
  // (e.g. explanation fields containing ```javascript ... ```),
  // extracting inner code instead of the actual JSON object.
  if (!cleaned.startsWith('{') && !cleaned.startsWith('[')) {
    // Try to match the content inside a top-level markdown code fence
    // (with any word-based language identifier like json, javascript, etc.)
    const codeBlockMatch = cleaned.match(/```[a-z]*\s*([\s\S]*?)\s*```/i);
    if (codeBlockMatch) {
      cleaned = codeBlockMatch[1].trim();
    }
  }

  return cleaned;
}

/**
 * Extracts question/front strings from Stage 2 raw text consolidated lists.
 *
 * @param {string} text Raw consolidated list.
 * @returns {string[]} List of question texts.
 */
export function parseStage2Questions(text) {
  if (typeof text !== 'string') return [];
  const lines = text.split('\n');
  const questions = [];
  for (const line of lines) {
    const trimmed = line.trim();
    // Match lines starting with "Front:", "Q:", or "Question:"
    // with optional bold markers or "Card X" prefix
    const regexPattern = '^(?:\\*\\*|)?(?:Card\\s*\\d+\\s*:?\\s*)?'
      + '(?:Front|Q(?:uestion)?)\\s*:\\s*(?:\\*\\*|)?(.*)';
    const questionRegex = new RegExp(regexPattern, 'i');
    const match = trimmed.match(questionRegex);
    if (match) {
      let qText = match[1].trim();
      qText = qText.replace(/\*\*$/, '').trim();
      if (qText) {
        questions.push(qText);
      }
    }
  }
  return questions;
}

/**
 * Audit checks that every Stage 2 question has a corresponding representation
 * in the Stage 3 card objects.
 *
 * @param {string[]} stage2Questions List of questions parsed from Stage 2.
 * @param {Array<Object>} stage3Cards List of cards from Stage 3 JSON.
 * @returns {string[]} Missing questions.
 */
export function verifyContentLoss(stage2Questions, stage3Cards) {
  const missingQuestions = [];
  if (!Array.isArray(stage3Cards)) {
    return [...stage2Questions];
  }

  for (const s2Q of stage2Questions) {
    const normalizedS2 = s2Q.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!normalizedS2) continue;

    let found = false;
    for (const card of stage3Cards) {
      if (card && typeof card.front === 'string') {
        const normalizedS3 = card.front.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (normalizedS3.includes(normalizedS2) || normalizedS2.includes(normalizedS3)) {
          found = true;
          break;
        }
      }
    }
    if (!found) {
      missingQuestions.push(s2Q);
    }
  }
  return missingQuestions;
}

/**
 * Executes Stage 3 of the pipeline: AJV Schema Enforcement.
 * Enforces schema compliance and translates consolidated text from Stage 2
 * into valid polymorphic JSON cards.
 * Uses an AJV compiler for validation and run a recovery re-prompt loop on failures.
 *
 * @param {Object} params
 * @param {string} params.runId Active execution run ID.
 * @param {string} params.questionId Unique identifier for this chunk/topic.
 * @param {string} params.synthesisResult Stage 2 consolidated text output.
 * @param {string} [params.cardType='standard'] Layout format ('standard' or 'mcq').
 * @param {string} [params.subject=''] Explicit subject name passed to the pipeline.
 * @param {Object} [params.prompts={}] Loaded prompts configuration from yaml file.
 * @param {Object} params.config The merged system configuration.
 * @param {Object} params.keys Loaded API keys.
 * @param {Map<string, OpenAI>} params.clients Initialized provider clients.
 * @param {Function} params.throttledFetch Concurrency-throttled fetch wrapper.
 * @param {number} [params.maxEnforcementRetries=5] Maximum recovery re-prompts on failures.
 * @returns {Promise<Object>} The conforming parsed JSON cards object.
 */
export async function runStage3({
  runId,
  questionId,
  synthesisResult,
  cardType = 'standard',
  subject = '',
  prompts = {},
  config,
  keys,
  clients,
  throttledFetch,
  maxEnforcementRetries = 5,
}) {
  if (typeof synthesisResult !== 'string' || !synthesisResult.trim()) {
    throw new Error('Stage 2 synthesis result is missing or empty');
  }

  // Retrieve schema enforcement model config
  const modelString = config?.pipeline?.schema_enforcement?.model;
  if (!modelString) {
    throw new Error('No schema enforcement model configured in config.pipeline.schema_enforcement.model');
  }

  const { provider, model } = resolveProviderModel(modelString);

  // Resolve Stage 3 prompts
  const resolvedPrompts = resolvePrompts(prompts, subject, cardType);
  const enforcementBase = resolvedPrompts.enforcement;

  // Inject target JSON Schema to guide enforcement
  const systemPrompt = `${enforcementBase}\n\nYou must output a JSON object conforming strictly to this JSON Schema:\n${JSON.stringify(CARD_JSON_SCHEMA, null, 2)}\n\nIMPORTANT: Output ONLY the raw JSON string. Do NOT wrap the JSON in markdown code blocks or backticks (e.g. do NOT use \`\`\`json ... \`\`\`).`;

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: `Consolidated Text Flashcard List:\n\n${synthesisResult}` },
  ];

  const stage2Questions = parseStage2Questions(synthesisResult);

  const useCompletionApi = config?.pipeline?.schema_enforcement?.use_completion_api === true;

  logger.debug`Starting Stage 3 (Schema Enforcement) for ${questionId} using model ${modelString} (max retries: ${maxEnforcementRetries}, useCompletionApi: ${useCompletionApi}). Parsed Stage 2 questions: ${stage2Questions.length}`;

  let attempt = 0;
  let lastErrorMsg = '';

  while (attempt < maxEnforcementRetries) {
    attempt++;
    logger.debug`Stage 3 attempt ${attempt}/${maxEnforcementRetries} for ${questionId}...`;
    const rawOutput = await callLLM({
      provider,
      model,
      messages,
      schema: CARD_ZOD_SCHEMA,
      config,
      keys,
      clients,
      throttledFetch,
      forceCompletionApi: useCompletionApi,
    });

    const cleanedOutput = cleanJsonOutput(rawOutput);
    let jsonObj;
    const errorsList = [];

    // 1. JSON Parsing Check
    try {
      jsonObj = JSON.parse(cleanedOutput);
      if (jsonObj) {
        jsonObj = removeNullValues(jsonObj);
        jsonObj = normalizeJsonObj(jsonObj, questionId, subject);
      }
    } catch (parseError) {
      logger.debug`Stage 3 JSON Parsing Error for attempt ${attempt}: ${parseError.message}`;
      errorsList.push(`JSON Parsing Error: ${parseError.message}`);
    }

    // 2. Zod Validation Check
    if (jsonObj) {
      const valResult = CARD_VALIDATION_SCHEMA.safeParse(jsonObj);
      if (!valResult.success) {
        const schemaErrors = valResult.error.issues.map((issue) => {
          const pathStr = issue.path.length > 0
            ? `/${issue.path.join('/')}`
            : '/';
          return `${pathStr}: ${issue.message}`;
        });
        logger.debug`Stage 3 Zod Validation failed for attempt ${attempt} with errors: ${schemaErrors.join(' | ')}`;
        errorsList.push(...schemaErrors);
      }
    }

    // 3. Content Loss Audit Check
    if (jsonObj) {
      const cards = jsonObj.cards || [];
      const missing = verifyContentLoss(stage2Questions, cards);
      if (missing.length > 0) {
        logger.debug`Stage 3 Content Loss Audit failed for attempt ${attempt}: ${missing.length} missing questions`;
        errorsList.push(
          `Content Loss Audit Error: The following questions from Stage 2 are missing in the Stage 3 JSON cards array:\n${
            missing.map((q) => `- ${q}`).join('\n')}`,
        );
      }
    }

    if (errorsList.length === 0) {
      logger.debug`Stage 3 enforcement succeeded on attempt ${attempt}. Generated ${jsonObj.cards?.length} card(s).`;
      // Success! Log the trace to pipeline_steps and return the conforming object
      addPipelineStep({
        runId,
        questionId,
        stage: 'enforcement',
        provider,
        model,
        inputData: JSON.stringify(messages),
        outputData: rawOutput,
      });

      upsertQuestionEntry({
        runId,
        questionId,
        currentStage: 'enforcement',
        latestPrompt: JSON.stringify(messages),
        latestResponse: rawOutput,
      });

      return jsonObj;
    }

    // Log failed attempt to pipeline_steps and run_questions for auditing/debugging
    const errorString = errorsList.join('\n');
    addPipelineStep({
      runId,
      questionId,
      stage: 'enforcement',
      provider,
      model,
      inputData: JSON.stringify(messages),
      outputData: rawOutput,
      status: 'failed',
      errors: errorString,
    });

    upsertQuestionEntry({
      runId,
      questionId,
      currentStage: 'synthesis', // Keep as synthesis so resumption knows it is not fully completed
      latestPrompt: JSON.stringify(messages),
      latestResponse: rawOutput,
      errors: errorString,
    });

    // Failed validation/audit: prepare feedback and append history for retry
    lastErrorMsg = errorsList.join('\n');
    logger.debug`Stage 3 attempt ${attempt} failed. Retrying... Errors:\n${lastErrorMsg}`;
    messages.push({ role: 'assistant', content: rawOutput });
    messages.push({
      role: 'user',
      content: `Your previous output did not conform to the schema or failed the Content Loss Audit. Please fix the following errors and output the entire, corrected JSON matching the schema:\n\n${lastErrorMsg}`,
    });
  }

  throw new Error(
    `Stage 3 Schema Enforcement failed after ${maxEnforcementRetries} attempts.\nLast Errors:\n${lastErrorMsg}`,
  );
}
